version: "3"
services:
  sftp:
    image: atmoz/sftp
    volumes:
      - hari-frontend-volume:/home/sftp
    ports:
      - "2222:22"
    depends_on:
      - frontend
    command: sftp:sftp:1001
  frontend:
    image: qweasd1z1z/hari-frontend-nginx-server
    volumes:
      - hari-frontend-volume:/repo
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=tonybear3.tk
volumes:
  hari-frontend-volume: