version: "3"
services:
  sftp:
    image: qweasd1z1z/sftp
    volumes:
      - hari-frontend-volume:/home/sftp
    ports:
      - "2222:22"
    depends_on:
      - frontend
#    command: sftp:sftp:1001
    environment:
      - USER=sftp
      - PASSWORD=sftp
  frontend:
    image: qweasd1z1z/hari-frontend-nginx-server
    volumes:
      - hari-frontend-volume:/repo
      - certificate-volume:/etc/ssl/acme
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=tonybear6.tk
volumes:
  hari-frontend-volume:
  certificate-volume: