version: "3"
services:
  sftp:
    image: sjourdan/alpine-sshd
    volumes:
      - hari-frontend-volume:/home/admin
    ports:
      - "2222:22"
    environment:
      - USER=admin
      - PASSWORD=admin
    depends_on:
      - frontend
  frontend:
    image: qweasd1z1z/hari-frontend-nginx-server
    volumes:
      - hari-frontend-volume:/repo
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=tonybear3.tk
volumes:
  hari-frontend-volume: